VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IRolledShapeControl"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Interface
'@Folder("SteelShapes.Controls")
Option Explicit

Public Sub PopulateComboBox(ByRef control As ComboBox)
End Sub

Public Sub PopulateListBox(ByRef control As MSForms.ListBox)
End Sub
